# Generated by Django 2.2.10 on 2021-11-15 15:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2021, 11, 15, 15, 14, 1, 732682, tzinfo=utc))),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, max_length=255)),
                ('choice_type', models.CharField(choices=[('open', 'Ответ текстом'), ('single', 'Один вариант ответа'), ('multiple', 'Несколько вариантов ответа')], max_length=10)),
            ],
        ),
    ]
