# Generated by Django 2.2.10 on 2021-11-15 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211115_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
