# Generated by Django 2.2.10 on 2021-11-15 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211115_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='poll',
        ),
    ]
