# Generated by Django 2.2.10 on 2021-11-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20211115_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
