# Generated by Django 2.2.10 on 2021-11-16 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0014_auto_20211116_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespondentUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session', models.CharField(blank=True, max_length=255, null=True)),
                ('authorized_credentials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_text', models.CharField(max_length=255, null=True)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Question')),
                ('respondent_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.RespondentUser')),
            ],
        ),
    ]
