# Generated by Django 2.2.10 on 2021-11-16 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_answer_respondentuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respondentuser',
            old_name='session',
            new_name='session_cookies',
        ),
    ]
