# Generated by Django 2.2.10 on 2021-11-16 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20211116_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondentuser',
            name='authorized_credentials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
