# Generated by Django 2.2.10 on 2021-11-16 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20211116_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='respondent_user_id',
            new_name='respondent_user',
        ),
    ]
